In [1]:
from tinysklearn.decomposition import PCA
from tinysklearn.model_selection import train_test_split
from tinysklearn.datasets import load_boston, load_breast_cancer, load_iris, load_digits
from tinysklearn.linear_model import LinearRegression, LogisticRegression
from tinysklearn.neighbors import KNeighborsClassifier
from tinysklearn.tree import DecisionTreeClassifier
from tinysklearn.preprocessing import StandardScaler

In [2]:
iris = load_iris()
x = iris.data
y = iris.target
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=666666)

In [3]:
dt = DecisionTreeClassifier()
dt.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [4]:
dt.score(x_test, y_test)

0.9333333333333333

In [5]:
knn_clf = KNeighborsClassifier()
knn_clf.fit(x_train, y_train)

KNN(k=3)

In [6]:
knn_clf.score(x_test,y_test)

0.9333333333333333

In [7]:
std = StandardScaler()
std.fit(x_train)
x_train_std = std.transform(x_train)
x_test_std = std.transform(x_test)

In [8]:
x_train_std[:10]

array([[-1.32658969,  0.32388202, -1.3030924 , -1.22608495],
       [ 0.42001743, -1.02406629,  1.13843148,  0.34191001],
       [ 0.29525977, -0.12543408,  0.68419448,  0.864575  ],
       [-0.95231674, -1.69804044, -0.16749989, -0.18075498],
       [-1.70086264, -0.12543408, -1.3030924 , -1.22608495],
       [ 1.04380568, -0.35009213,  0.57063523,  0.21124377],
       [ 1.04380568, -0.12543408,  0.45707598,  0.34191001],
       [-0.20377083, -0.35009213,  0.00283898,  0.21124377],
       [-0.82755909,  1.67183033, -1.13275352, -1.22608495],
       [-0.20377083, -1.24872434,  0.17317786, -0.05008873]])

In [9]:
x_train[:10]

array([[4.7, 3.2, 1.3, 0.2],
       [6.1, 2.6, 5.6, 1.4],
       [6. , 3. , 4.8, 1.8],
       [5. , 2.3, 3.3, 1. ],
       [4.4, 3. , 1.3, 0.2],
       [6.6, 2.9, 4.6, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [5.1, 3.8, 1.6, 0.2],
       [5.6, 2.5, 3.9, 1.1]])

In [10]:
knn_clf = KNeighborsClassifier()
knn_clf.fit(x_train_std, y_train)
knn_clf.score(x_test_std,y_test)

0.9333333333333333

In [11]:
cancer = load_breast_cancer()
x = cancer.data
y = cancer.target
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=666666)

In [12]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

F:\GitHub\MachineLearningAlgorithm\TinySklearn\tinysklearn\linear_model.py:39: RuntimeWarning: overflow encountered in exp
  return 1. / (1. + np.exp(-z))
F:\GitHub\MachineLearningAlgorithm\TinySklearn\tinysklearn\linear_model.py:44: RuntimeWarning: divide by zero encountered in log
  return - np.sum(y_train * np.log(y_hat) + (1 - y_train) * np.log(1 - y_hat)) / len(y_train)
F:\GitHub\MachineLearningAlgorithm\TinySklearn\tinysklearn\linear_model.py:44: RuntimeWarning: invalid value encountered in multiply
  return - np.sum(y_train * np.log(y_hat) + (1 - y_train) * np.log(1 - y_hat)) / len(y_train)
F:\GitHub\MachineLearningAlgorithm\TinySklearn\tinysklearn\linear_model.py:57: RuntimeWarning: invalid value encountered in double_scalars
  if (abs(J(self._theta, X_b, y_train) - J(last_theta, X_b, y_train)) < 1e-7):


0.35398230088495575

In [13]:
boston = load_boston()
x = boston.data
y = boston.target
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=666666)

In [14]:
lr = LinearRegression()
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.7078840086221798

In [15]:
digits = load_digits()
x = digits.data
y = digits.target
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=666666)

In [16]:
pca = PCA(2)
pca.fit(x_train)
x_train_2 = pca.transform(x_train)
x_train_2[0]

array([-17.29143881,  -7.30458359])

In [17]:
x_train_2

array([[-17.29143881,  -7.30458359],
       [ 17.78194423,   5.21534217],
       [ 15.84324404,   0.27900505],
       ...,
       [ -3.33123025,  10.67479035],
       [-19.950048  , -11.46807609],
       [  2.56630399,   1.03389618]])

In [18]:
import matplotlib.pyplot as plt
for i in range(10):
    plt.scatter(x_train_2[y_train==i,0],x_train_2[y_train==i,1])
plt.show()

<Figure size 640x480 with 1 Axes>

In [19]:
import numpy as np
a = np.array([1,3,3])
len(a)

3

In [20]:
a = a.reshape(-1,1)
a.ndim
a

array([[1],
       [3],
       [3]])